config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
     root to: "top#index"
     resources :events
     resources :users 
     end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    has_many :groopings, through: :event_groopings
    has_many :event_groopings, dependent: :destroy
    mount_uploader :image, ImageUploader
    validates :image,:name,:place,:text,:link,:scedule, presence: true
    
    def self.search(search)
     if search
      Event.where(['name LIKE ? or place LIKE ?', "%#{search}%","%#{search}%"])
     else
      Event.all
     end
    end 
   
    
    
    #以下、タグ機能実装過程
    #def save_groopings(tags)
       # current_tags = self.groopings.pluck(:name) unless self.groopings.nil?
       #old_tags = current_tags - tags
        #new_tags = tags - current_tags
   # end 
    
     # Destroy old taggings:
    #old_tags.each do |old_name|
     #    self.groopings.delete Grooping.find_by(name:old_name)
  #  end
    
     # Create new taggings:
    #new_tags.each do |new_name|
     #   event_grooping = Grooping.find_or_create_by(name:new_name)
      #  self.groopings << event_grooping
   # end
end 

app/models/event_grooping.rb
class EventGrooping < ApplicationRecord
    belongs_to :event
    belongs_to :grooping
end

app/models/grooping.rb
class Grooping < ApplicationRecord
    has_many :events, through: :events_groopings
    has_many :events_groopings,dependent: :destroy
end

app/models/musical_instrument.rb
class MusicalInstrument < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :events
  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :move_to_index, except: [:index, :show]
    
    def index
        @events = Event.includes(:user).search(params[:search]).order("created_at DESC ").page(params[:page]).per(10)
        @events = Event.includes(:user).search(params[:search1]).order("created_at DESC ").page(params[:page]).per(10)
        #元の書き方@events = Event.includes(:user).order("created_at DESC ").page(params[:page]).per(10)
    end 
  
    def new
        @event=Event.new
    end
    
    def create
        @event=Event.create(create_params)
        #grooping_list = params[:grooping_list].split(",")
        if @event.save
         #   @event.save_groopings(grooping_list)
           redirect_to events_url
        else
            render action: :new
        end
        #unless @event.save　　　#render action: :new　　　#end
    end 
    
    def destroy
        event = Event.find(params[:id])
        event.destroy if event.user_id == current_user.id
    end
    
    def edit
        @event = find_event_by_id
       # @grooping_list = @event.groopings.pluck(:name).join(",")
    end
    
    def update
        @event = Event.find(params[:id])
        if @event.user_id == current_user.id
            @event.update(create_params)
        end
        unless @event.save
        render action: :edit
        end
    end
    
    
    def show
        @event = find_event_by_id
        @user = User.find_by(id: @event.user_id)  #event詳細ページにuser情報表示できるようにひもづけ
       
    end
    
    private
    def create_params
        params.require(:event).permit(:image,:name,:place,:text,:scedule,:link).merge(user_id: current_user.id)

    end
    
    def find_event_by_id
        Event.find(params[:id])
    end
    
    def move_to_index
        redirect_to action: :index unless user_signed_in?
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
        @events = Event.includes(:user).search(params[:search]).order("created_at DESC ").page(params[:page]).per(10)
        @events = Event.includes(:user).search(params[:search1]).order("created_at DESC ").page(params[:page]).per(10)
        @user= User.all
    end
    
    def new
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user= User.find(params[:id])
        @events= Event.where(user_id: @user.id).page(params[:page]).per(10)
    end
    
    def edit
        @user=User.find(params[:id])
      
    end
    
    def update
        @user=User.find(params[:id])
        if @user.id == current_user.id
            @user.update(user_params)
        end
        unless @user.save
        render action: :edit
        end 
    end


    private
    def user_params
       params.require(:user).permit(:image,:name,:text,:link)         #.merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_error_message.html.erb
<% if @event.errors.any? %>
    <h3>入力した内容にエラーが<%= @event.errors.count %>件あります</h3>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %> 

app/views/events/_event.html.erb
<div class="events">
         <%=link_to (image_tag event.image.url),"/events/#{event.id}"%>
         <div class="event_name">
                  <%=link_to (event.name),"/events/#{event.id}",{class: "event_name"}%>
         </div>
         <div class="event_place">
                  <%=link_to (event.place),"/events/#{event.id}",{class: "event_name"}%>
         </div>
         <div class="event_scedule">     
                  <%=link_to (event.scedule),"/events/#{event.id}",{class: "event_name"}%>
         </div>
       
  
     <div class="user_name">
         <%= link_to "投稿者#{event.user.name}", user_path(event.user) ,{class: "event_name"}%>
    </div>
</div>

app/views/events/_form.html.erb
<div class="events-post-container">
 <%= form_for (@event) do |f| %>
   <%= render "events/error_message" %>
    <div class ="input" >
       <p><%= f.label "イベント画像" %></P>
       <%= f.file_field :image %><br><br>
       
       <p><%= f.label "イベント名" %></p> 
       <p><%= f.text_field :name, placeholder: 'イベント名'%></p>
       
       <p><%= f.label "開催地" %></p>
       <p><%= f.text_field :place, placeholder: '開催地'%></p>
   
       <p><%= f.label "イベント詳細" %></p>
       <%= f.text_field :text, placeholder: '詳細'%></p>
       
       <P><%= f.label "イベントURL" %></p>
       <p><%= f.text_field :link, placeholder: 'リンク先'%></p>
       
       <p><%= f.label "開催日" %></p>
       <p><%= f.date_field_tag :scedule %></p>
       
       <p><%= f.label "open" %></p>
       <p><%= f.time_select :scedule, {}, class: 'form-control' %></p>
       
       <p><%= f.label "start" %></p>
       <p><%= f.time_select :scedule, {}, class: 'form-control' %></p>
       
       <p><%= f.submit class: "btn btn-primary withrippple", value: "投稿する" %></p>
       <%#<div class="events-tags-filed">
         <%= f.label "開催団体"
         <ul id="event-tags">
         </ul>
       </div>%>
        <%#<p><%= button_tag type: "submit", class: "btn btn--block" do >
                 投稿する<i class="icon-arrow-right"></i></p>
        <% end %>
    </div>
 <% end %>
</div>



  

app/views/events/create.html.erb
<div class="events-success">
    <div class="success-triangle"></div>
        <h2 class="success-header">投稿が完了しました</h2>
       
        <a class="btn" href="/">トップに戻る</a>
    </div>
</div>

app/views/events/destroy.html.erb
<div class="contents row">
    <div class="success">
        <h3>
            削除が完了しました。
        </h3>
    <a class="btn" href="/users/<%= current_user.id%>">mypageへ戻る</a>
    </div>
</div>

app/views/events/edit.html.erb
<div class="events">
    <div class="events-triangle"></div>
    <h2 class="events-header">イベント編集</h2>
   
   <%= render "form" %>
  
</div>

app/views/events/index.html.erb
<div class="events-index">
    <% @events.each do |event| %>
       <%= render partial: "event", locals: {event: event} %>　
    <% end %>
    
    <%= paginate(@events) %>
     
   
</div>

app/views/events/new.html.erb
  <div class="events-post">
    <div class="events-post-triangle"></div>
    <h2 class="events-post-header">イベント投稿</h2>
   
   <%= render "form" %>
  
</div>

app/views/events/show.html.erb
<div class="f-container">
    <div class="events-show" >
        <%= image_tag @event.image.url %>
        <div class="information">
            <div class="event-title"><p>イベント名</p></div>
                <h1><%= @event.name%></h1>
            <div class="event-title"><p>place</p></div>
                 <h3><%= @event.place%></h3>
            <div class="event-title"><p>price</p></div>
                <h3><%= @event.price%></h3>
            <div class="event-title"><p>scedule</p></div>
                <h3><%= @event.scedule%></h3>
            <div class="event-title"><p>イベント詳細</p></div>
                <h3><%= @event.text %></h3>
            <div class="event-title"><p>イベントリンク</p></div>
                <h3><%= @event.link %></h3>
        </div>
    </div>


    <h3>投稿者</h3>　  
    <div class="user_info">
                <%= image_tag @user.image.url %>
            <div class='user_text'>
                <h2><%= "#{@user.name}" %></h2>
                
            </div>
    </div>
    <div class="user_zone"  >
       <% if user_signed_in? && current_user.id == @event.user_id %>
        <div class="btn-square-shadow">
            <li>
                <%=link_to '編集', "/events/#{@event.id}/edit", method: :get %>
            </li>
        </div>
        <div class="btn-square-shadow">
            <li>
                <%= link_to '削除', "/events/#{@event.id}",method: :delete %>
            </li>
        </div>
        <% end %>
    </div>
</div>

app/views/events/update.html.erb
<div class="events-success">
    <div class="success-triangle"></div>
        <h2 class="success-header">更新が完了しました</h2>
        
        <a class="btn" href="/users/<%= current_user.id%>">mypageへ戻る</a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musiker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
     <!-- flexslider導入 -->
 <link rel="stylesheet" href="flexslider.css" type="text/css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script src="jquery.flexslider.js"></script>
<script type="text/javascript" charset="utf-8">
$(window).load(function() {
  
  // The slider being synced must be initialized first
  $('#carousel').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 210,
    itemMargin: 5,
    asNavFor: '#slider'
  });
 
  $('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel"
  });
});

(function() {
 
  // store the slider in a local variable
  var $window = $(window),
      flexslider = { vars:{} };
 
  // tiny helper function to add breakpoints
  function getGridSize() {
    return (window.innerWidth < 600) ? 2 :
           (window.innerWidth < 900) ? 3 : 4;
  }
 
  $(function() {
    SyntaxHighlighter.all();
  });
 
  $window.load(function() {
    $('.flexslider').flexslider({
      animation: "slide",
      animationLoop: false,
      itemWidth: 210,
      itemMargin: 5,
      minItems: getGridSize(), // use function to pull in initial value
      maxItems: getGridSize() // use function to pull in initial value
    });
  });
 
  // check grid size on resize event
  $window.resize(function() {
    var gridSize = getGridSize();
 
    flexslider.vars.minItems = gridSize;
    flexslider.vars.maxItems = gridSize;
  });
}());
</script>

    <script src="http://web-pixy.com/js/jquery.flexslider-min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= stylesheet_link_tag "users" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
     <!-- コード追加　Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header >
      <div class="inner">
        <div class="flexbox">
          <h1 class="logo-img">
            <a href="/">Musiker</a>
          </h1>
          
          <%= form_tag events_path, :method => 'get' do %>
            <div class="header_search">
              <a><%= text_field_tag :search1, params[:search],placeholder: "キーワード入力"%></a>
              <input type="submit" value="&#xf002"  class="main_search">
              <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
            </div>
          <% end %>
         
          <%# ドロワーhtml%>
        <div class='drawer'>
          <input id="drawer-checkbox" type="checkbox">
          <label id="drawer-icon" for="drawer-checkbox"><span></span></label>
          <label id="drawer-close" for="drawer-checkbox"></label>
          <div id="drawer-content">
            <li><a href="/">ホーム</a></a></li>
           <li><a href="/events">イベント一覧</a></li>
            <% if user_signed_in? %>
              <li><a href="/users/<%= current_user.id%>">mypage</a></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <li><a href="/events/new">投稿する</a></li>
            <% else %>
              <li><a href="/users/sign_up">会員登録</a></li>
              <li><a href=" /users/sign_in">ログイン</a></li>
            <% end %>
          </div>
        </div>
         
         
         <nav class="nav-global">
            <ul class="flexbox">
               <li><a href="/events">イベント一覧</a></li>
            <% if user_signed_in? %>
              <li><a href="/users/<%= current_user.id%>">mypage</a></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <li><a href="/events/new">投稿する</a></li>
            <% else %>
              <li><a href="/users/sign_up">会員登録</a></li>
              <li><a href=" /users/sign_in">ログイン</a></li>
            <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
  
     <%= yield %>
    
  </body>
  
</html>

app/views/top/index.html.erb
 <main role="main-search">
      <section class="section">
         <%= form_tag events_path, :method => 'get' do %>
          <%= text_field_tag :search1, '', class: 'main_search' %>
          <input  type="submit" value="&#xf002" class="main_search" /></td>
          <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
          <% end %>
  
          
      <%#元々の検索フォーム
      <form id="form1" action="https://e5f4290b9b1f4589af242e8d6c5dca04.vfs.cloud9.ap-northeast-1.amazonaws.com/?s=#">
        <input id="sbox"  id="s" name="s" type="text" placeholder="キーワードを入力" />
        <input id="sbtn" type="submit" value="検索" /></td>
        </form>%>
      </section>
    <%#イベントのピックアップ%>  
      <section class="pickup">
         <div class='pickup_font'>
             <h2 class='pp_font'>Pick up Event</h2>
             <div class='pickup_information'>開催間近、人気のコンサートです
             </div>
         </div>
          <div class="flexslider carousel">
            <ul class="slides">
               <% @events.each do |event| %>
              <li>
                 <%=link_to (image_tag event.image.url),"/events/#{event.id}"%>
              </li>
               <% end %>
            </ul>
          </div>
     
     <%# userのピックアップ%>     
        <div class='pickup_font'>
            <h2 class='pp_font'>Pick up Artist</h2>
                <div class='pickup_information'>今、人気のアーティスト
                </div>
            <div class="flexslider carousel">
                <ul class="slides">
                     <% @user.each do |user| %>
                          <li> 
                            <%=link_to (image_tag user.image.url),"/users/#{user.id}" %>
                          </li>
                         
                     <% end %>
                </ul>
          </div>
          
         </div>
      </section>

      <section class="comming">

      </section>
    </main>
    
 

app/views/users/edit.html.erb
<div class="users-edit">
    <div class="users-edit-triangle"></div>
        <h2 class="users-edit-header">ユーザー情報を編集する</h2>
            <div class="users-edit-container">
                <%= form_for (@user) do |f| %>
                    <div class="input">
                        <%= f.label "プロフィール写真" %>
                        <%= f.file_field :image %><br><br>
                        
                        <%= f.label "名前" %>
                        <%= f.text_field :name, placeholder: 'name'%><br><br>
                        
                        <%= f.label "自己紹介" %>
                        <%= f.text_field :text, placeholder: 'introduction'%><br><br>
                        
                        <%= f.label 'link編集' %>
                        <%= f.text_field :link, placeholder: 'link'%><br><br>
                         
                        <%= f.submit class: 'btn btn-primary withripple', value: '編集する ' %>
                    </div>
                <% end %>
            </div>
</div>
<%= stylesheet_link_tag "users" %>

app/views/users/show.html.erb
<%= stylesheet_link_tag "users" %>
 
<div class="mypage">
    <div class="user_info">
        <span><%= image_tag @user.image.url %></span>
        <div class='user_name'><h1><%= "#{@user.name}" %></h1></div>
    </div>
    
     <div id="social-container">
              <a href="#"><div class="social-button fb">
                <i class="fa fa-facebook fa-lg"></i><span>Facebook</span>
              </div></a><!--
              --><a href="#"><div class="social-button yt">
                <i class="fa fa-youtube fa-lg"></i><span>YouTube</span>
              </div></a><!--
              --><a href="#"><div class="social-button tw">
                <i class="fa fa-twitter fa-lg"></i><span>Twitter</span>
              </div></a><!--
              --><a href="#"><div class="social-button ig">
                <i class="fa fa-instagram fa-lg"></i><span>Instagram</span>
              </div></a><!--
              -->
    </div>
        
    <div class="user_text">
        <div class="user_title"><P>Introduce</P></div>
            <h3><%= "#{@user.text}" %> </h3>
    </div>

    <div class="user_events">
        <div class="event-title"><p>イベント一覧</p></div>
        <div class="f-container-eventindex">
            <% @events.each do |event| %>
        <div class="events">
            <%=link_to (image_tag event.image.url),"/events/#{event.id}"%>
        <div class="name">
            <%=link_to (event.name),"/events/#{event.id}",{class: "event_name"}%>
        </div>
        <div class="price-scedule">
            <%=link_to (event.price),"/events/#{event.id}",{class: "event_name"}%><br>
            <%=link_to (event.scedule),"/events/#{event.id}",{class: "event_name"}%>
        </div>
        </div>
        <% end %>
    </div>
    <%= paginate(@events) %>
</div>
 <div class="user_zone"  >
     <% if user_signed_in?  %>
     <div class="btn-square-shadow">
        <li>
            <%=link_to 'mypage編集',"/users/#{@user.id}/edit", method: :get %>
        </li>
    </div>
    <div class="btn-square-shadow">
        <li>
            <%=link_to 'メールアドレス、パスワード変更','/users/edit', method: :get %>
        </li>
     </div>
    <div class="btn-square-shadow">
        <li>
             <%= link_to 'イベント投稿', "/events/new",method: :get%>
        </li>
     </div>
     <% end %>
     
   
     
</div>

app/views/users/update.html.erb
<div class="events-success">
    <div class="success-triangle"></div>
        <h2 class="success-header">更新が完了しました</h2>
        
        <a class="btn" href="/users/<%= current_user.id%>">mypageへ戻る</a>
    </div>
</div>